### ISSUE TITLE
Make sure all known replacements are included.

### ISSUE THREAD

**Issue by pmcelhaney** [madflow/jquery-slugify#5]
In my version of slugify users have contributed many language-specific replacements over the years. We should make sure this copy isn't missing anything from that list.

 https://github.com/pmcelhaney/jQuery-Slugify-Plugin/blob/master/jquery.slugify.js#L16

**Comment by kontur** [comment]
Also, some locales treat replacement logic differently for the same letter. For example in German, transcribe `ä` to `ae` is correct, whereas in Finnish you'd transcribe `ä` to `a`.

**Comment by pmcelhaney** [comment]
@kontur Yes, see https://github.com/madflow/jquery-slugify/issues/6

**Comment by kontur** [comment]
Ah yea right, missed that there was a separate issue already. :+1:
