### ISSUE TITLE
Support the HTML lang attribute

### ISSUE THREAD

**Issue by pmcelhaney** [madflow/jquery-slugify#6]
Sometimes the correct substitution is language-dependent. For example "ä" should become either "ae" or "a" depending on the language. 

We should look for a [lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) attribute in HTML to determine what to do.

**Comment by madflow** [comment]
Okay - you suggest something like this:

https://github.com/pid/speakingurl/blob/master/lib/index.js#L859

?

I would suggest to leave this up to the implementation of this plugin by the third party developer and add a "lang" settings flag.

**Comment by pmcelhaney** [comment]
Yes, exactly. 

A `lang` option in the plugin would be good. If no `lang` option is specified, I think we should look for a `lang` attribute in the HTML.
