### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by valkirilov** [madflow/jquery-slugify#7]
Hello, 

after the last update the plugin stopped working for me.

I receive this error:
![slugify-error](https://cloud.githubusercontent.com/assets/1233496/7652274/9d2578b6-fb13-11e4-9dd1-11b5b88fb89d.png)

**Comment by madflow** [comment]
Hi, you have to include speakingurl as a dependency. 

    <script src="jquery.js"></script>
    <script src="speakingurl.min.js"></script>
    <script src="slugify.min.js"></script>


If you use bower - it will be installed as dependency for you. If you do not user bower - you can dowload speakingurl here: https://github.com/pid/speakingurl

Please consult the latest Readme for the changes.

**Comment by valkirilov** [comment]
Yup, I've missed that.
Thanks for your fast response.
