### ISSUE TITLE
not support Unicode language

### ISSUE THREAD

**Issue by ericfavoni** [madflow/jquery-slugify#8]
Thanks For Good plugin. i work for persian language like this : سلام بر شما . But your plugin not support persian Or arabic language.

**Comment by madflow** [comment]
Can you elaborate what you mean by "not support.." ?

We use https://github.com/pid/speakingurl for the transliteration.

When I insert سلام بر شما in our demo page:

http://madflow.github.io/jquery-slugify/

I get:

slam-br-shma

I cannot comment if this is transliterated good enough - but "something" is there :D . If this is faulty or needs work - all requests for the language support should be placed in this repo: https://github.com/pid/speakingurl.

**Comment by ericfavoni** [comment]
i need to change سلام بر شما to سلام-بر-شما

**Comment by madflow** [comment]
The transliterated string is per default in this range of chars: A-Za-z0-9_-

Check https://github.com/pid/speakingurl/blob/master/lib/speakingurl.js#L41

If you need something else - maybe this is plugin+speakingurl is simply not suitable for your use case.
